/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CandlestickChart: typeof import('./components/common/comp/CandlestickChart.vue')['default']
    CArea: typeof import('./components/common/comp/CArea.vue')['default']
    CBodyArea: typeof import('./components/common/comp/CBodyArea.vue')['default']
    CSearchItem: typeof import('./components/common/comp/CSearchItem.vue')['default']
    Headers: typeof import('./components/common/comp/Headers.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SAutoInput: typeof import('./components/common/comp/SAutoInput.vue')['default']
    SButton: typeof import('./components/common/comp/SButton.vue')['default']
    SGridInput: typeof import('./components/common/comp/SGridInput.vue')['default']
    SGridSelect: typeof import('./components/common/comp/SGridSelect.vue')['default']
    SLabelInput: typeof import('./components/common/comp/SLabelInput.vue')['default']
  }
}
